LICENSE, README.md
Readme includes author and license sections. License replaced with
approved contents.
Fixes https://github.com/auth0/node-xml-encryption/issues/13
=> Replace license and fix readme

package.json
use the latest version of node-forge to resolve the following error:
```sh
/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/util.js:1320
_queryVariables = parse(window.location.search.substring(1));
^
TypeError: Cannot read property 'search' of undefined
at Object.util.getQueryVariables (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/util.js:1320:50)
at Array.initModule (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/log.js:306:26)
at Array.module.exports (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/log.js:359:14)
at …
```
=> Use a latest version of node-forge

lib/xmlenc.js, test/xmlenc.encryptedkey.js
Onelogin uses triple DES encryption algorithm to encrypt their SAML response and xml-encryption fails to decrypt the response (issue solution described here: https://github.com/nodejs/node/issues/2794#issuecomment-139436581)
This PR applies de1ec53b8e0ff3f59a55c14abf5516f9b115ca31 and 26c391699a7e4bffac63b22ada47f309e06c70ac for 3DES algorithm.
I also DRYed the decrypt code and unit tests.
=> Fix autopadding issue with for 3DES algorithm

.travis.yml, lib/xmlenc.js, package.json, test/xmlenc.encryptedkey.js
We want to make sure that Node 6 and 8 are supported today, and as future changes are introduced.
Given [the changes to the default encoding in the cryptographic functions introduced in Node 6](https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6#crypto), I wasn't sure if `xmlenc.decryptKeyInfo()` worked properly in Node 6.
=> Make sure that Node 6-8 is supported

README.md, lib/xmlenc.js, test/xmlenc.encryptedkey.js
This addresses #45 
Add option to disallow insecure algorithms. 
Update deprecated Buffer constructors.
#45 
Included unit tests for the changes.
=> Add support to disallow insecure algorithms

.travis.yml, lib/templates/encrypted-key.tpl.xml.js, lib/templates/keyinfo.tpl.xml.js, lib/utils.js, package-lock.json, package.json
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
The purpose of this PR is to make it easier to use xml-encryption with a bundler, like webpack.
This PR inlines the template files used by `utils.js` as JavaScript files instead of using `fs.readFileSync()` to load them.
This allows webpack to statically include the templates, instead of depending on hacks like that described in #55.
See #55 
This code adds no new functionality. Tests pass locally.
=> Inline templates

lib/xmlenc.js, test/xmlenc.encryptedkey.js
Fix typo for options.keyEncryptionAlgorithm. 
🚫 This requires a major version bump due to backwards incompatible change.
=> Fix typo for keyEncryptionAlgorithm option

README.md, package.json
Deprecating support for node 4 and 6. 
https://github.com/auth0/node-xml-encryption/pull/59
=> Deprecate node 4/6

README.md, lib/xmlenc.js, test/xmlenc.encryptedkey.js
Fix a callback to match callback error signature
Add additional tests
Fix README and test typos
#63
=>  Fix a missing check in encryption for encrypt call

README.md, lib/utils.js, lib/xmlenc.js, package-lock.json, package.json, test/xmlenc.encryptedkey.js
The warning is piped to stderr using console.warn().
Added option to turn it off; defaults to true.
#66
=> feat: Add warning when insecure algorithm is used.

lib/utils.js, package-lock.json, package.json
Fix for styling; no behavior impact.
=> fix(utils): fix accidental duplicate export.

package-lock.json, package.json
`sinon`, a mocking framework used in tests, is listed as a production dependency. `sinon` is bigger than all of the rest of the code and tests and dependencies combined, so it's a shame shipping it as a production dependency.
Change it to a dev dependency, only available for tests.
```
faux@astoria:~/clone/node-xml-encryption% g grep sinon | fgrep -v package-lock
package.json:    "sinon": "^9.0.2"
test/xmlenc.encryptedkey.js:var sinon = require('sinon');
test/xmlenc.encryptedkey.js:    consoleSpy = sinon.spy(console, 'warn');
```
=> feat: sinon is a dev dependency

package-lock.json, package.json
Updates `node-forge` to the latest version to address a security issue in the dependency and bumps a new version. Fixes #75  
The `node-forge` new version drops support for node 4 but `node-xml-encryption` already specifies the node engine >=8. As such, a new patch version will be released.
https://snyk.io/vuln/SNYK-JS-NODEFORGE-598677 
All tests pass successfully.
=> Update node-forge to the latest version

package-lock.json, package.json
By submitting a PR to this repository, I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
Routine upgrade of the abovementioned dependencies to bring it in-line with xml-crypto, so that projects that depend on both packages would keep transitive dependencies to a minimum.
Relying on CI tests
=> Update xpath, xmldom, y18n, lodash

lib/xmlenc.js, package-lock.json, package.json, test/xmlenc.integration.js
The package is now scoped under @xmldom. See https://github.com/xmldom/xmldom/pull/278
This fixes security vulnerability CVE-2021-32796
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
Fixes CVE-2021-32796
https://nvd.nist.gov/vuln/detail/CVE-2021-32796
https://snyk.io/vuln/SNYK-JS-XMLDOM-1534562
https://github.com/xmldom/xmldom/pull/278
Tests pass
=> Update xmldom to 0.7.0

README.md, lib/xmlenc.js, package-lock.json, package.json
This requires dropping support for node 8, which is probably fine since
node 8 is EoL since December 31, 2019.
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
Drop node-forge (which is a huge dep), use native nodejs crypto.
About node 8 support
https://blog.risingstack.com/update-nodejs-8-end-of-life-no-support/
Node Crypto
https://nodejs.org/api/crypto.html#crypto_crypto_publicencrypt_key_buffer
https://nodejs.org/api/crypto.html#crypto_crypto_privatedecrypt_privatekey_buffer
I updated first the …
=> Replace node-forge by native node crypto.

package-lock.json, package.json
1. Prepares for release 2.0.0, which drops support for Node 8. 
2. Also updates package lock file to version 2 which is [backwards compatible to version 1](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion)
=> release 2.0.0

package-lock.json, package.json
add semgrep support
uodate xmldom
breaking changes in xmldom:
https://github.com/xmldom/xmldom/pull/310
https://github.com/xmldom/xmldom/pull/314
https://github.com/xmldom/xmldom/pull/307
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking …
=> release 3.0.0

package-lock.json, package.json
Bump @xmldom/xmldom to 0.8.5 to remediate a [security advisory](https://github.com/xmldom/xmldom/security/advisories/GHSA-crh6-fp67-6883)
Closes #102 
Per unit tests
=> Bump @xmldom/xmldom to 0.8.5

package-lock.json, package.json
Releasing v3.0.2
PR included in the new version:
-  https://github.com/auth0/node-xml-encryption/pull/107
Changes included in the new version:
- @xmldom/xmldom is updated to 0.8.5 to remediate a security advisory. See xmldom changelog for more: https://github.com/xmldom/xmldom/blob/master/CHANGELOG.md#084
=> release v3.0.2

.github/workflows/test.yml, README.md, package.json
Add test runs during PR merge. 
Also updated the README on node version support. 
Node 18 does not support triple des algorithm (listed as insecure) due to 
>  TypeError: RSA_PKCS1_PADDING is no longer supported for private decryption, this can be reverted with --security-revert=CVE-2023-46809
=> add test to github workflow

README.md, lib/templates/keyinfo.tpl.xml.js, lib/xmlenc.js, package-lock.json, package.json, test/xmlenc.encryptedkey.js
Add support for encryption key OAEP digest method using `http://www.w3.org/2000/09/xmldsig#sha256` and `http://www.w3.org/2000/09/xmldsig#sha512` in addition to SHA1.
=> Add support for sha256/512 encryption key OAEP digest methods
